### ISSUE TITLE
ASI Support Crash On Startup

### ISSUE THREAD

**Issue by 9Lincoln20** [fr-Pursuit/AsiSupport#2] opened 2018-12-13 02:08 UTC
[crash-13-12-2018-11.55.17.txt](https://github.com/fr-Pursuit/AsiSupport/files/2674255/crash-13-12-2018-11.55.17.txt)

I have installed the latest version of ASI Support until the new scripthookv comes out for GTA 1604, rage 0.64 and I get a crash on startup.  The crash log is attached.

**Comment by fr-Pursuit** [comment] 2018-12-13 17:20
This issue is caused by AdvancedVHook. It appears to be incompatible with ASI Support 0.3. I'll try to fix this issue in the next release.

**Comment by fr-Pursuit** [comment] 2018-12-13 20:13
Turns out AdvancedHookV.asi is not an ASI script but a simple library used by ELS. The latest ELS version doesn't need it, and use AdvancedHookV.dll. You can therefore delete AdvancedHookV.asi, and update ELS if AdvancedHookV.dll is not present in your directory.

I might update the conversion process to handle this case at a later date.

**Comment by DoubleDoppler** [comment] 2018-12-14 22:56
Unfortunately removing the AdvancedHookV.asi doesn't resolve the problem. This is a very handy mod and an essential whilst ScripthookV isn't updated, please resolve if possible

**Comment by fr-Pursuit** [comment] 2018-12-14 23:31
@DoubleDoppler Please send me your ragepluginhook.log file by pasting its content on pastebin.com and posting the link here.

**Comment by DoubleDoppler** [comment] 2018-12-14 23:39
https://pastebin.com/AQQ0ayTt
https://pastebin.com/pd3sbQ4b

**Comment by fr-Pursuit** [comment] 2018-12-14 23:46
@DoubleDoppler The crash appears to be caused by GTAV.HeapAdjuster, another file which is not an ASI script despite having the .asi extension. It seems I need to make the plugin detect and ignore this kind of file. I'm working on an update atm.

**Comment by DoubleDoppler** [comment] 2018-12-14 23:51
I'll remove it and keep you updated

**Comment by DoubleDoppler** [comment] 2018-12-15 00:27
Correct, thank you for the insight. I think updating would be a great step forward but so far, this script has saved us from the dreaded wait.

**Comment by fr-Pursuit** [comment] 2018-12-15 00:51
Fixed in 0.3.2

**Closed as completed by fr-Pursuit** 2018-12-15 00:51 UTC
