### ISSUE TITLE
getGameVersion() returns -1

### ISSUE THREAD

**Issue by ikt32** [fr-Pursuit/AsiSupport#3] opened 2018-12-17 22:36 UTC
See title :)

**Comment by fr-Pursuit** [comment] 2018-12-18 07:50
For now, it's the expected behavior. Indeed, many scripts (like Simple Trainer) seem to check if getGameVersion() != -1 to perform operations which lead to a crash (for exemple, accessing something in memory that was moved since the last update).

Having getGameVersion() return -1 is the only way I've found to make these plugins compatible. But I understand it's impractical if you use it to verify if your script is running on the latest version, which is why I'll try to find a better way to provide compatibility with these scripts.

Either way, this will be fixed when the next SHV version is released and every script gets an update to fix the crashes mentioned above.

**Comment by ikt32** [comment] 2018-12-18 08:15
Hmm, something I do for one of my scripts is to read the file version and have an internal map, but that would require updating this plugin every update.

Considering RPH always only works for the newest release, couldn't you return some very high number?

**Comment by fr-Pursuit** [comment] 2018-12-18 08:17
The problem isn't about the number being high or not, it's about it being != -1

**Comment by sjaak327** [comment] 2018-12-18 09:11
I can shed a little background on this. Trainer is using some globals, and only a few memory offsets. In case of the memory offsets (the snow), I use logic as in if (version < latest+2) at the time of compile, so that when a new patch comes out, the code won't run as crash protection.

In case of globals, I do the opposite. I run the right global for the right version (backwards compatiblity) but for both the recording UI and the prevent DLC vehicles from disappearing I do if version > latest version. This means that if a new patch comes out, the code will run. Often this is not a problem, as the global for recording UI almost never is updated (it HAS updated this patch) and the prevent dlc disappearance has also updated this patch. I think it crashes on this global, as it's called uncontidionally .

I CAN change this behaviour and revert to the same system as the snow. I will do this for the new version. Downside, if new patch comes, global does not change, it will not run. Upside is, normally I have trainer out before scripthook, especialy if you keep developing this quicker as Blade updates his scripthook. Ragehook has Always been quicker as blade.

**Comment by sjaak327** [comment] 2018-12-18 09:14
Oh and indeed as it stands currently, returning a high number will not solve the issue. I bet many mods actually do this. And I bet it is global that prevents de-spawning of DLC vehicles. I will revert back to crash protection over functionality in the next version of trainer, so that at least for my mod you don't have to return -1. But I guess some mod makers would prefer to take the chance. Also because of the long time Blade sometimes needs to update it.

**Comment by fr-Pursuit** [comment] 2018-12-18 10:58
This will be fixed in the next update, and an option will allow users to switch to the current behaviour in case it causes problems.

**Comment by fr-Pursuit** [comment] 2019-06-22 16:28
Fixed in 0.3.3

**Closed as completed by fr-Pursuit** 2019-06-22 16:28 UTC
