### ISSUE TITLE
Infinite black loading screen

### ISSUE THREAD

**Issue by RealSkyr0** [fr-Pursuit/AsiSupport#4] opened 2020-04-02 14:32 UTC
Me and a lot of others have an infinite black loading screen right as we load the plugin.
This is while manually loading it through the RPH console, not automatically, since then the game crashes.
Help would be much appreciated!

**Comment by RealSkyr0** [comment] 2020-04-02 14:37
[Screenshot](https://i.imgur.com/afleL7Y.png)

**Comment by Sebboo** [comment] 2020-04-02 16:55
Not an issue with AsiSupport, but your .asi scripts that you're running. Most likely Menyoo.

**Comment by fr-Pursuit** [comment] 2020-04-04 11:19
This issue was resolved in the RPH Discord server thanks to @Sebboo. It was caused by Menyoo.

**Closed as completed by fr-Pursuit** 2020-04-04 11:19 UTC
