### ISSUE TITLE
ELS Issue

### ISSUE THREAD

**Issue by G35Matt** [fr-Pursuit/AsiSupport#6] opened 2021-03-17 23:50 UTC
I'm getting an error loading ELS using ASI Support

Here are the relevant lines from RagePluginHook.log:
[3/17/2021 6:48:07 PM.920] ASI Support For RAGE Plugin Hook: [18:48:07] [INFO] Plugin "ELS" loaded successfully.
[3/17/2021 6:48:07 PM.927] ASI Support For RAGE Plugin Hook: [18:48:07] [INFO] Starting new GameFiber: "ELS-main"
[3/17/2021 6:48:11 PM.588] ASI Support For RAGE Plugin Hook: [18:48:11] [ERROR] GameFiber "ELS-main" has crashed: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
[3/17/2021 6:48:11 PM.588] at AsiSupport.ASI.AsiThread.RunFiber()

**Comment by fr-Pursuit** [comment] 2021-03-17 23:53
Have you reloaded ASI Support ? If so, please note that some plugins such as ELS cannot be reloaded once they've already been loaded at least once, and will crash with an `AccessViolationException` if you attempt to do so.

**Comment by G35Matt** [comment] 2021-03-17 23:58
Yes I tried reloading ASI Support as well as unloading all ASI plugins and loading just ELS, got the same error

**Comment by fr-Pursuit** [comment] 2021-03-18 00:02
That's exactly what I'm saying. If ELS is loaded, then crashed and / or is unloaded, you *have* to restart your game for it to work again. Simply reloading it (or reloading ASI Support as a whole) would make it crash with an `AccessViolationException`.

**Comment by G35Matt** [comment] 2021-03-18 00:07
Alright I'll give it a shot, I noticed that ASI Support gets unloaded by RPH to prevent freezing if it is set to run at startup so I'll disable it and run it once I'm in game

**Comment by fr-Pursuit** [comment] 2021-03-18 00:09
If necessary, you can increase the plugin termination threshold in the RPH settings (accessible when you launch RPH)

**Comment by G35Matt** [comment] 2021-03-18 00:16
I can try that as well, when I loaded it through the console I saw that RPH is unloading it because of the ELS-main fiber so it looks like the issue still persists when it's loaded for the first time

**Comment by G35Matt** [comment] 2021-03-18 00:24
Another update, with an increased plugin termination threshold, LoadAllPluginsOnStartup set to False in the ASI Support cfg, and manually loading only ELS, it is working, however the framerate dips to about 10 or so FPS.

**Comment by swamperjon** [comment] 2021-03-18 14:53
i was useing scripthook v for els and stuff none would work after 2245 update, REMOVED Scripthookv  Installed ASI Support, RESTARTED PC... All works great THANKS FOR YOUR WORK ITS Awesome!!!! If Done Like I did they should'nt be Problems.

**Comment by fr-Pursuit** [comment] 2021-03-18 20:37
Unfortunately the FPS drop is to be expected. By design, ASI Support can't be as fast as ScriptHookV

**Comment by swamperjon** [comment] 2021-03-18 22:56
i use els and other mods works fine not seen any problems dont see no differance yet

**Comment by fr-Pursuit** [comment] 2022-05-04 11:59
Since your initial problem was fixed, I'm closing this issue.

As for the FPS drop, as I previously said, it is due to the way AsiSupport works. There is unfortunately no way to increase performance without creating an entirely new and independant scripting framework.

**Closed as completed** 2022-05-04 11:59 UTC
